# ~/.config/herdr/config.toml

onboarding = false

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[experimental]
pane_history = false
switch_ascii_input_source_in_prefix = true

[theme]
name = "terminal"

auto_switch = false
[keys]
focus_pane_left = ["prefix+h", "ctrl+alt+h"]
focus_pane_down = ["prefix+j", "ctrl+alt+j"]
focus_pane_up = ["prefix+k", "ctrl+alt+k"]
focus_pane_right = ["prefix+l", "ctrl+alt+l"]
previous_tab = ["prefix+p", "ctrl+alt+p"]
next_tab = ["prefix+n", "ctrl+alt+n"]
new_tab = ["prefix+c", "ctrl+alt+c"]
split_vertical = ["prefix+v", "ctrl+alt+d"]
split_horizontal = ["prefix+minus", "ctrl+alt+shift+d"]
zoom = ["prefix+z", "ctrl+alt+z"]
previous_workspace = ["ctrl+alt+up"]
next_workspace = ["ctrl+alt+down"]
